version: '3.3'

services:
  #post_db:
    #build: ../src/ui
  #  image: mongo:${SERVICE_MONGO}
  #  volumes:
  #    - post_db:/data/db
  #  networks:
  #    - reddit
  #    - back_net
  
  blackbox-exporter:
    image: prometheus/blackbox_exporter:v0.20.0
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"' 

  mongo-exporter:
    image:  percona/mongodb_exporter:v2.26.0 
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
     
    
  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'

  ui:
    build: ../src/ui
    image: ${USER_NAME}/ui:${SERVICE_UI}
    ports:
      - ${PORT_UI}:${PORT_UI}/${PROTOCOL}
    networks:
      #- reddit
      - front_net

  post:
    build: ../src/post-py
    image: ${USER_NAME}/post:${SERVICE_POST}
    networks:
      #- reddit
      - front_net
      - back_net 
   
  comment:  
    build: ../src/comment
    image: ${USER_NAME}/comment:${SERVICE_COMMENT}
    networks:
      #- reddit
      - front_net
      - back_net

  prometheus:
    image: ${USER_NAME}/prometheus
    volumes:
      #- ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d' # Задаем время хранения метрик в 1 день
    ports:
      - 9090:9090
    networks:
      #- reddit
      - front_net
      - back_net

volumes:
  post_db:

volumes:
  prometheus_data:

networks:
  #reddit:
  front_net:
    driver: bridge
  back_net:
    driver: bridge
